/**
 * Session repository — drizzle-based data access.
 * Path fields MUST be normalized via normalizePath() before write.
 *
 * Session "config snapshot" semantics:
 * - model / thinkingLevel / systemPrompt / appendSystemPrompt / tools / workspacePath are COPIED
 *   from agent on session creation
 * - Subsequent changes update session row only (do NOT mutate agent row)
 */

import { count, desc, eq } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import type { DB } from '../db/init.js';
import { sessions, agents } from '../db/schema.js';
import type { SessionDTO, SessionStatus, AgentConfig } from '@pi-agent-platform/shared-types';
import { normalizePath } from '../utils/normalize-path.js';

function rowToDTO(row: typeof sessions.$inferSelect): SessionDTO {
  return {
    id: row.id,
    agentId: row.agentId,
    model: row.model,
    thinkingLevel: row.thinkingLevel ?? undefined,
    config: row.config ? (JSON.parse(row.config) as AgentConfig) : undefined,
    piSessionPath: row.piSessionPath,
    /** @deprecated — see SessionStatus. Status is no longer mutated; use worker state. */
    status: row.status as SessionStatus,
    title: row.title ?? undefined,
    createdAt: row.createdAt,
    lastActiveAt: row.lastActiveAt,
    worker: null, // overwritten by routes via workerPool.toSummary()
  };
}

export function createSessionRepo(db: DB) {
  return {
    list(agentId?: string): SessionDTO[] {
      const rows = agentId
        ? db.select().from(sessions).where(eq(sessions.agentId, agentId)).all()
        : db.select().from(sessions).all();
      return rows.map(rowToDTO);
    },

    /**
     * Paged list ordered by last_active_at DESC (newest first).
     * Returns the requested page plus the total count.
     *
     * `workspacePath` filter joins `agents` (sessions doesn't snapshot the path —
     * only `piSessionPath`). For MVP we filter in-memory after join: agents table
     * is small, sessions table is bounded, and the join is a single index lookup
     * per session via `idx_sessions_agent_id`. Total is computed against the
     * filtered set so the page count matches what's actually shown.
     */
    listPaged(opts: {
      agentId?: string;
      workspacePath?: string;
      search?: string;
      offset: number;
      limit: number;
    }): { sessions: SessionDTO[]; total: number } {
      const baseWhere = opts.agentId ? eq(sessions.agentId, opts.agentId) : undefined;

      const query = db
        .select({ s: sessions, ws: agents.workspacePath })
        .from(sessions)
        .leftJoin(agents, eq(sessions.agentId, agents.id))
        .orderBy(desc(sessions.lastActiveAt));

      const rawRows = baseWhere
        ? query.where(baseWhere).all()
        : query.all();

      let filtered = rawRows;
      if (opts.workspacePath) {
        const target = normalizePath(opts.workspacePath);
        // Include sessions whose agent's workspacePath is the target itself
        // OR a subdirectory of the target (prefix match with trailing / separator).
        filtered = filtered.filter((r) => {
          if (!r.ws) return false; // orphan session (agent deleted) — exclude
          const wp = normalizePath(r.ws);
          return wp === target || wp.startsWith(target + '/');
        });
      }
      if (opts.search) {
        const searchLower = opts.search.toLowerCase();
        filtered = filtered.filter((r) => {
          const title = (r.s.title ?? '').toLowerCase();
          const id = r.s.id.toLowerCase();
          return title.includes(searchLower) || id.includes(searchLower);
        });
      }

      const total = filtered.length;
      const paged = filtered.slice(opts.offset, opts.offset + opts.limit).map((r) => rowToDTO(r.s));
      return { sessions: paged, total };
    },

    get(id: string): SessionDTO | undefined {
      const row = db.select().from(sessions).where(eq(sessions.id, id)).get();
      return row ? rowToDTO(row) : undefined;
    },

    /**
     * Create a session by snapshotting config from an agent.
     * Caller provides sessionId (pre-generated by master placeholder API)
     * and piSessionPath (returned by worker createSession IPC).
     */
    createFromAgent(input: {
      sessionId: string;
      agentId: string;
      piSessionPath: string;
      title?: string;
      /** Override agent.model with the worker's resolved actual model (e.g. "deepseek/deepseek-v4-flash"). */
      modelOverride?: string;
    }): SessionDTO | undefined {
      const agent = db.select().from(agents).where(eq(agents.id, input.agentId)).get();
      if (!agent) return undefined;

      const now = Date.now();
      const row = {
        id: input.sessionId,
        agentId: agent.id,
        model: input.modelOverride ?? agent.model,
        thinkingLevel: agent.thinkingLevel ?? null,
        config: agent.config ?? null,
        piSessionPath: input.piSessionPath,
        status: 'active' as const,
        title: input.title ?? null,
        createdAt: now,
        lastActiveAt: now,
      };
      db.insert(sessions).values(row).run();
      return this.get(input.sessionId);
    },

    update(id: string, patch: Partial<Omit<SessionDTO, 'id' | 'agentId' | 'createdAt' | 'status'>>): SessionDTO | undefined {
      const existing = this.get(id);
      if (!existing) return undefined;
      const updates: Partial<typeof sessions.$inferInsert> = { lastActiveAt: Date.now() };
      // Explicit `title` key (even with value undefined) = clear → write NULL.
      // The old `!== undefined` guard silently skipped clears, so DB kept the
      // old title and next-load heal resurrected it on the pi side too
      // (clear was broken end-to-end; found while extracting session-ops).
      if ('title' in patch) updates.title = patch.title ?? null;
      if (patch.model !== undefined) updates.model = patch.model;
      if (patch.thinkingLevel !== undefined) updates.thinkingLevel = patch.thinkingLevel;
      if (patch.config !== undefined) updates.config = patch.config ? JSON.stringify(patch.config) : null;
      db.update(sessions).set(updates).where(eq(sessions.id, id)).run();
      return this.get(id);
    },

    /** Mark a session as archived (status is deprecated; use isAlive from worker pool instead). */
    archive(id: string): SessionDTO | undefined {
      const existing = this.get(id);
      if (!existing) return undefined;
      db.update(sessions)
        .set({ status: 'archived' as const })
        .where(eq(sessions.id, id))
        .run();
      return this.get(id);
    },

    /** Generate a placeholder session id (for the placeholder API). */
    /** Hard-delete a session row. Returns true if a row was removed.
     *  Note: this does NOT touch the pi session file on disk — callers
     *  (the route handler) own file deletion + worker cleanup. */
    delete(id: string): boolean {
      const result = db.delete(sessions).where(eq(sessions.id, id)).run();
      return result.changes > 0;
    },

    newSessionId(): string {
      return randomUUID();
    },
  };
}

export type SessionRepo = ReturnType<typeof createSessionRepo>;